FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && apt-get install -y \
    build-essential \
    libsasl2-dev \
    python3-dev \
    libldap2-dev \
    libssl-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
COPY frontend_app.py .
COPY templates ./templates
COPY flag.txt .
EXPOSE 5000
CMD ["python", "frontend_app.py"]
