FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY frontend_app.py .
COPY templates ./templates
COPY flag.txt .
EXPOSE 5000
CMD ["python", "frontend_app.py"]
